merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('band/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('listing/', views.listing, name='listing'),
    path('listing/<int:id>/',  views.listing_detail, name='listing-detail'),
    path('listing/add/', views.listing_create, name='listing-create'),
    path('listing/<int:id>/change/', views.listing_update, name='listing-update'),
    path('listing/<int:id>/delete/', views.listing_delete, name='listing-delete'),

    path('about-us/', views.about, name='a-propos'),
    path('contact-us/', views.contact, name='contact'),
    path('help/', views.help),

    path('confirmation/', views.email_sent, name='email-sent')

    
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    name = models.fields.CharField(max_length=100)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2024)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        METAL = 'MT'
        EDM = 'EDM'
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    def __str__(self):
        return f'{self.name}'
    

class Listing(models.Model):
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2024)], 
        default=True,
        blank= True
    )
    class Types(models.TextChoices):
        RECORDS = 'R'
        CLOTHINGS = 'C'
        POSTERS = 'P'
        DIVERS = 'D'
    types = models.fields.CharField(choices=Types.choices, max_length=5)
    def __str__(self):
        return f'{self.title}'
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
   class Meta:
     model = Band
     exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):
   class Meta:
      model = Listing
      exclude = ('sold',)

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', 
                  {'bands': bands})

def band_detail(request, id):
  band = Band.objects.get(id=id) 
  return render(request,
          'listings/band_detail.html',
          {'band': band})

def listing(request): #page listing avec les objets
    listing = Listing.objects.all()
    return render(request, 'listings/listing.html',
                  {'listing': listing})

def listing_detail(request, id):
    listing_detail = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listing_detail' : listing_detail})


def about(request):
    return render(request, 'listings/about.html')

def contact(request):
    return render(request, 'listings/contact.html')

def help(request):
    return HttpResponse('<p>Besoin de nous ?</p>')

def contact(request):
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    form = ContactUsForm()  # ajout d’un nouveau formulaire ici
    return render(request,
          'listings/contact.html',
          {'form': form})  # passe ce formulaire au gabarit
    

def contact(request):
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
        return redirect('email-sent')
    else:
        form = ContactUsForm()

    return render(request,
            'listings/contact.html',
            {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
            'listings/band_create.html',
            {'form': form})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request, 
                  'listings/listing_create.html', 
                  {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_update.html',
                {'form': form})

def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                'listings/listing_update.html',
                {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('band_list')
    return render(request,
           'listings/band_delete.html',
           {'band': band})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listing')
    return render(request,
           'listings/listing_delete.html',
           {'listing': listing})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
<html>
    <head><title>Merchex</title></head>
    <body>
        <h1>A propos</h1> 
        <p>Nous adorons merch ! </p>
    </body>
</html>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>Créer un fiche groupe</h2>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
   {% if band.official_homepage %}
   <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
   {% endif %}
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% for listing_detail in band.listing_set.all %}
<a href="{% url 'listing-detail' listing_detail.id %}"><p>Articles du groupe</p></a>
{% endfor %}

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Hello Django !</h1>

<p>Mes groupes préférés sont :</p>

<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[modifier] 
            - <a href="{% url 'band-delete' band.id %}">[supprimer]</a></a>
    </li>
   {% endfor %}
</ul>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>
 {% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title></head>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <body>
        <header><a href="{% url 'band-list' %}">Bands</a><a href="{% url 'contact' %}">Contact</a><a href="{% url 'a-propos' %}">A propos</a><a href="{% url 'listing' %}">Listing</a></header> 
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Merci pour votre message !</h1>

{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}
{% load static %}

{% block content %}
<h1>Hello Django !</h1>

<p>Mes groupes préférés sont :</p>

<ul>
    {% for band in bands %}
        <li>
            {{ band.name }}
        </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Articles en vente :</h1>

<ul>
    {% for listing_detail in listing %}
    <li><a href="{% url 'listing-detail' listing_detail.id %}">{{ listing_detail.title }}</a>
       - <a href="{% url 'listing-update' listing_detail.id %}">[modifier] 
        - <a href="{% url 'listing-delete' listing_detail.id %}">[supprimer]</a></li>
   {% endfor %}
</ul>
<a href="{% url 'listing-create' %}">Créer un nouveau objet en vente</a>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>Créer un nouveal article</h2>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer l'article'</h1>

<p>Etes-vous sûr de vouloir supprimer cet article : {{ listing.title }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>{{ listing_detail.title }}</h2>

<ul>
 <li>descriptioon : {{ listing_detail.description }}</li>
 <li>Vendu : {{ listing_detail.sold|yesno }}</li>
 <li>Types : {{ listing_detail.types }}</li>
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'listing' %}">Retour à tous les articles en vente</a>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>
 {% endblock %}
 